        
// Keep existing structure but rename to avoid conflicts
const groundedSheetsVariantsOriginal = [
  // Single quantity variants
  { id: 1, size: "Twin", color: "Obsidian Grey", quantity: 1 },
  { id: 2, size: "Twin", color: "Chateau Ivory", quantity: 1 },
  { id: 3, size: "Double", color: "Obsidian Grey", quantity: 1 },
  { id: 4, size: "Double", color: "Chateau Ivory", quantity: 1 },
  { id: 5, size: "Queen", color: "Obsidian Grey", quantity: 1 },
  { id: 6, size: "King", color: "Obsidian Grey", quantity: 1 },
  { id: 7, size: "Queen", color: "Chateau Ivory", quantity: 1 },
  { id: 8, size: "King", color: "Chateau Ivory", quantity: 1 },
  { id: 9, size: "Twin", color: "Scribe Blue", quantity: 1 },
  { id: 10, size: "Double", color: "Scribe Blue", quantity: 1 },
  { id: 11, size: "Queen", color: "Scribe Blue", quantity: 1 },
  { id: 12, size: "King", color: "Scribe Blue", quantity: 1 },
  { id: 13, size: "Twin", color: "Verdant Sage", quantity: 1 },
  { id: 14, size: "Double", color: "Verdant Sage", quantity: 1 },
  { id: 15, size: "Queen", color: "Verdant Sage", quantity: 1 },
  { id: 16, size: "King", color: "Verdant Sage", quantity: 1 },
  { id: 17, size: "Single", color: "Obsidian Grey", quantity: 1 },
  { id: 18, size: "Cali King", color: "Obsidian Grey", quantity: 1 },
  { id: 19, size: "Single", color: "Chateau Ivory", quantity: 1 },
  { id: 20, size: "Cali King", color: "Chateau Ivory", quantity: 1 },
  { id: 21, size: "Single", color: "Scribe Blue", quantity: 1 },
  { id: 22, size: "Cali King", color: "Scribe Blue", quantity: 1 },
  { id: 23, size: "Single", color: "Verdant Sage", quantity: 1 },
  { id: 24, size: "Cali King", color: "Verdant Sage", quantity: 1 },
  
  // 2-pack variants
  { id: 25, size: "Single", color: "Obsidian Grey", quantity: 2 },
  { id: 26, size: "Single", color: "Chateau Ivory", quantity: 2 },
  { id: 27, size: "Single", color: "Scribe Blue", quantity: 2 },
  { id: 28, size: "Single", color: "Verdant Sage", quantity: 2 },
  { id: 29, size: "Twin", color: "Obsidian Grey", quantity: 2 },
  { id: 30, size: "Twin", color: "Chateau Ivory", quantity: 2 },
  { id: 31, size: "Twin", color: "Scribe Blue", quantity: 2 },
  { id: 32, size: "Twin", color: "Verdant Sage", quantity: 2 },
  { id: 33, size: "Double", color: "Obsidian Grey", quantity: 2 },
  { id: 34, size: "Double", color: "Chateau Ivory", quantity: 2 },
  { id: 35, size: "Double", color: "Scribe Blue", quantity: 2 },
  { id: 36, size: "Double", color: "Verdant Sage", quantity: 2 },
  { id: 37, size: "Queen", color: "Obsidian Grey", quantity: 2 },
  { id: 38, size: "Queen", color: "Chateau Ivory", quantity: 2 },
  { id: 39, size: "Queen", color: "Scribe Blue", quantity: 2 },
  { id: 40, size: "Queen", color: "Verdant Sage", quantity: 2 },
  { id: 41, size: "King", color: "Obsidian Grey", quantity: 2 },
  { id: 42, size: "King", color: "Chateau Ivory", quantity: 2 },
  { id: 43, size: "King", color: "Scribe Blue", quantity: 2 },
  { id: 44, size: "King", color: "Verdant Sage", quantity: 2 },
  { id: 45, size: "Cali King", color: "Obsidian Grey", quantity: 2 },
  { id: 46, size: "Cali King", color: "Chateau Ivory", quantity: 2 },
  { id: 47, size: "Cali King", color: "Scribe Blue", quantity: 2 },
  { id: 48, size: "Cali King", color: "Verdant Sage", quantity: 2 },
  
  // 3-pack variants
  { id: 49, size: "Single", color: "Obsidian Grey", quantity: 3 },
  { id: 50, size: "Single", color: "Chateau Ivory", quantity: 3 },
  { id: 51, size: "Single", color: "Scribe Blue", quantity: 3 },
  { id: 52, size: "Single", color: "Verdant Sage", quantity: 3 },
  { id: 53, size: "Twin", color: "Obsidian Grey", quantity: 3 },
  { id: 54, size: "Twin", color: "Chateau Ivory", quantity: 3 },
  { id: 56, size: "Twin", color: "Scribe Blue", quantity: 3 },
  { id: 57, size: "Twin", color: "Verdant Sage", quantity: 3 },
  { id: 58, size: "Double", color: "Obsidian Grey", quantity: 3 },
  { id: 59, size: "Double", color: "Chateau Ivory", quantity: 3 },
  { id: 60, size: "Double", color: "Scribe Blue", quantity: 3 },
  { id: 61, size: "Double", color: "Verdant Sage", quantity: 3 },
  { id: 62, size: "Queen", color: "Obsidian Grey", quantity: 3 },
  { id: 63, size: "Queen", color: "Chateau Ivory", quantity: 3 },
  { id: 64, size: "Queen", color: "Scribe Blue", quantity: 3 },
  { id: 65, size: "Queen", color: "Verdant Sage", quantity: 3 },
  { id: 66, size: "King", color: "Obsidian Grey", quantity: 3 },
  { id: 67, size: "King", color: "Chateau Ivory", quantity: 3 },
  { id: 68, size: "King", color: "Scribe Blue", quantity: 3 },
  { id: 69, size: "King", color: "Verdant Sage", quantity: 3 },
  { id: 70, size: "Cali King", color: "Obsidian Grey", quantity: 3 },
  { id: 71, size: "Cali King", color: "Chateau Ivory", quantity: 3 },
  { id: 72, size: "Cali King", color: "Scribe Blue", quantity: 3 },
  { id: 73, size: "Cali King", color: "Verdant Sage", quantity: 3 },
  
  // Exit 10% discount variants - Single quantity
  { id: 74, size: "Single", color: "Obsidian Grey", quantity: 1, discount: "Exit 10%" },
  { id: 75, size: "Single", color: "Chateau Ivory", quantity: 1, discount: "Exit 10%" },
  { id: 76, size: "Single", color: "Scribe Blue", quantity: 1, discount: "Exit 10%" },
  { id: 77, size: "Single", color: "Verdant Sage", quantity: 1, discount: "Exit 10%" },
  { id: 78, size: "Twin", color: "Obsidian Grey", quantity: 1, discount: "Exit 10%" },
  { id: 79, size: "Twin", color: "Chateau Ivory", quantity: 1, discount: "Exit 10%" },
  { id: 80, size: "Twin", color: "Scribe Blue", quantity: 1, discount: "Exit 10%" },
  { id: 81, size: "Twin", color: "Verdant Sage", quantity: 1, discount: "Exit 10%" },
  { id: 82, size: "Double", color: "Obsidian Grey", quantity: 1, discount: "Exit 10%" },
  { id: 83, size: "Double", color: "Chateau Ivory", quantity: 1, discount: "Exit 10%" },
  { id: 84, size: "Double", color: "Scribe Blue", quantity: 1, discount: "Exit 10%" },
  { id: 85, size: "Double", color: "Verdant Sage", quantity: 1, discount: "Exit 10%" },
  { id: 86, size: "Queen", color: "Obsidian Grey", quantity: 1, discount: "Exit 10%" },
  { id: 87, size: "Queen", color: "Chateau Ivory", quantity: 1, discount: "Exit 10%" },
  { id: 88, size: "Queen", color: "Scribe Blue", quantity: 1, discount: "Exit 10%" },
  { id: 89, size: "Queen", color: "Verdant Sage", quantity: 1, discount: "Exit 10%" },
  { id: 90, size: "King", color: "Obsidian Grey", quantity: 1, discount: "Exit 10%" },
  { id: 91, size: "King", color: "Chateau Ivory", quantity: 1, discount: "Exit 10%" },
  { id: 92, size: "King", color: "Scribe Blue", quantity: 1, discount: "Exit 10%" },
  { id: 93, size: "King", color: "Verdant Sage", quantity: 1, discount: "Exit 10%" },
  { id: 94, size: "Cali King", color: "Obsidian Grey", quantity: 1, discount: "Exit 10%" },
  { id: 95, size: "Cali King", color: "Chateau Ivory", quantity: 1, discount: "Exit 10%" },
  { id: 96, size: "Cali King", color: "Scribe Blue", quantity: 1, discount: "Exit 10%" },
  { id: 97, size: "Cali King", color: "Verdant Sage", quantity: 1, discount: "Exit 10%" },
  
  // Exit 10% discount variants - 2-pack
  { id: 98, size: "Single", color: "Obsidian Grey", quantity: 2, discount: "Exit 10%" },
  { id: 99, size: "Single", color: "Chateau Ivory", quantity: 2, discount: "Exit 10%" },
  { id: 100, size: "Single", color: "Scribe Blue", quantity: 2, discount: "Exit 10%" },
  { id: 101, size: "Single", color: "Verdant Sage", quantity: 2, discount: "Exit 10%" },
  { id: 102, size: "Twin", color: "Obsidian Grey", quantity: 2, discount: "Exit 10%" },
  { id: 103, size: "Twin", color: "Chateau Ivory", quantity: 2, discount: "Exit 10%" },
  { id: 104, size: "Twin", color: "Scribe Blue", quantity: 2, discount: "Exit 10%" },
  { id: 105, size: "Twin", color: "Verdant Sage", quantity: 2, discount: "Exit 10%" },
  { id: 106, size: "Double", color: "Obsidian Grey", quantity: 2, discount: "Exit 10%" },
  { id: 107, size: "Double", color: "Chateau Ivory", quantity: 2, discount: "Exit 10%" },
  { id: 108, size: "Double", color: "Scribe Blue", quantity: 2, discount: "Exit 10%" },
  { id: 109, size: "Double", color: "Verdant Sage", quantity: 2, discount: "Exit 10%" },
  { id: 110, size: "Queen", color: "Obsidian Grey", quantity: 2, discount: "Exit 10%" },
  { id: 111, size: "Queen", color: "Chateau Ivory", quantity: 2, discount: "Exit 10%" },
  { id: 112, size: "Queen", color: "Scribe Blue", quantity: 2, discount: "Exit 10%" },
  { id: 113, size: "Queen", color: "Verdant Sage", quantity: 2, discount: "Exit 10%" },
  { id: 114, size: "King", color: "Obsidian Grey", quantity: 2, discount: "Exit 10%" },
  { id: 115, size: "King", color: "Chateau Ivory", quantity: 2, discount: "Exit 10%" },
  { id: 116, size: "King", color: "Scribe Blue", quantity: 2, discount: "Exit 10%" },
  { id: 117, size: "King", color: "Verdant Sage", quantity: 2, discount: "Exit 10%" },
  { id: 118, size: "Cali King", color: "Obsidian Grey", quantity: 2, discount: "Exit 10%" },
  { id: 119, size: "Cali King", color: "Chateau Ivory", quantity: 2, discount: "Exit 10%" },
  { id: 120, size: "Cali King", color: "Scribe Blue", quantity: 2, discount: "Exit 10%" },
  { id: 121, size: "Cali King", color: "Verdant Sage", quantity: 2, discount: "Exit 10%" },
  
  // Exit 10% discount variants - 3-pack
  { id: 122, size: "Single", color: "Obsidian Grey", quantity: 3, discount: "Exit 10%" },
  { id: 123, size: "Single", color: "Chateau Ivory", quantity: 3, discount: "Exit 10%" },
  { id: 124, size: "Single", color: "Scribe Blue", quantity: 3, discount: "Exit 10%" },
  { id: 125, size: "Single", color: "Verdant Sage", quantity: 3, discount: "Exit 10%" },
  { id: 126, size: "Twin", color: "Obsidian Grey", quantity: 3, discount: "Exit 10%" },
  { id: 127, size: "Twin", color: "Chateau Ivory", quantity: 3, discount: "Exit 10%" },
  { id: 128, size: "Twin", color: "Scribe Blue", quantity: 3, discount: "Exit 10%" },
  { id: 129, size: "Twin", color: "Verdant Sage", quantity: 3, discount: "Exit 10%" },
  { id: 130, size: "Double", color: "Obsidian Grey", quantity: 3, discount: "Exit 10%" },
  { id: 131, size: "Double", color: "Chateau Ivory", quantity: 3, discount: "Exit 10%" },
  { id: 132, size: "Double", color: "Scribe Blue", quantity: 3, discount: "Exit 10%" },
  { id: 133, size: "Double", color: "Verdant Sage", quantity: 3, discount: "Exit 10%" },
  { id: 134, size: "Queen", color: "Obsidian Grey", quantity: 3, discount: "Exit 10%" },
  { id: 135, size: "Queen", color: "Chateau Ivory", quantity: 3, discount: "Exit 10%" },
  { id: 136, size: "Queen", color: "Scribe Blue", quantity: 3, discount: "Exit 10%" },
  { id: 137, size: "Queen", color: "Verdant Sage", quantity: 3, discount: "Exit 10%" },
  { id: 138, size: "King", color: "Obsidian Grey", quantity: 3, discount: "Exit 10%" },
  { id: 139, size: "King", color: "Chateau Ivory", quantity: 3, discount: "Exit 10%" },
  { id: 140, size: "King", color: "Scribe Blue", quantity: 3, discount: "Exit 10%" },
  { id: 141, size: "King", color: "Verdant Sage", quantity: 3, discount: "Exit 10%" },
  { id: 142, size: "Cali King", color: "Obsidian Grey", quantity: 3, discount: "Exit 10%" },
  { id: 143, size: "Cali King", color: "Chateau Ivory", quantity: 3, discount: "Exit 10%" },
  { id: 144, size: "Cali King", color: "Scribe Blue", quantity: 3, discount: "Exit 10%" },
  { id: 145, size: "Cali King", color: "Verdant Sage", quantity: 3, discount: "Exit 10%" }
];
